repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.4
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: [--fix, --select, I]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: pas-format
        name: DelphiScript format
        language: system
        entry: "'C:/Program Files (x86)/Embarcadero/Studio/23.0/bin/Formatter.exe'"
        files: \.pas$
