- id: find-altium
  name: Find AD installation
  entry: altiumate --altium-path
  description: "Finds Altium Designer installations"
  pass_filenames: false
- id: altium-run
  name: Run in AD
  entry: altiumate run
  files: \\.(PrjPcb|SchDoc|PcbDoc)$
  description: "Runs a script in Altium Designer"
- id: update-readme
  name: Update README.md
  entry: altiumate readme
  files: \\.(PrjPcb|md)$
  pass_filenames: false
  description: "Updates the README.md file with requested project parameters"